import Head from "next/head";
import styles from "../styles/Home.module.css";
import Layout from "../components/general/layout";
import Landing from "../components/exclusive/homePage/landing";
import Events from "../components/exclusive/homePage/events";
import Speakers from "../components/exclusive/homePage/speakers";
import Sponsors from "../components/exclusive/homePage/sponsors";

const prefix = "/pyconir2021";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={prefix + "/favicon.ico"} />
      </Head>
      <Layout>
        <Landing />
        <Events />
        <Speakers />
        <Sponsors />
      </Layout>
    </div>
  );
}
